### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Arjun with billing account",
  "address": "Bangalore, India",
  "dateOfBirth": "2001-03-05",
  "email": "arjun_billing_account_kproducer@example.com",
  "registeredDate": "2015-03-05"
}


###