### Create a new patient entity
POST http://lb-4237d841.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Arjun Kafka Test",
  "address": "Bangalore, India",
  "dateOfBirth": "2001-03-05",
  "email": "kafka_cloud@example.com",
  "registeredDate": "2015-03-05"
}


###